#include <iostream>
#include <string>
#include <spdlog/spdlog.h>
#include "car_sales_processor.hpp"
#include <chrono>
#include <fmt/core.h>

void print_table(GroupedSumList table, std::string first_col_heading)
{
    int num_cols = 1;
    std::string heading_string = fmt::format("|{:^20}|", first_col_heading);
    bool heading_printed = false;
    for (auto row: table) {
        std::string row_string = fmt::format("|{:^20}|", row.first);
        for (auto cols : row.second) {
            if (!heading_printed) {
                heading_string += fmt::format("{:^20}|", cols.first);
                num_cols++;
            }
            row_string += fmt::format("{:^20}|", cols.second);
        }
        if (!heading_printed) {
            spdlog::info("+{}+",std::string(20*num_cols + (num_cols-1), '-'));
            spdlog::info("{}", heading_string);
            spdlog::info("+{}+",std::string(20*num_cols + (num_cols-1), '-'));
            heading_printed = true;
        }
        spdlog::info("{}", row_string);
    }
    spdlog::info("+{}+",std::string(20*num_cols + (num_cols-1), '-'));
}

int WORKER_THREADS = 8;

int main() {
    spdlog::info("Staring Car Sales Processor");

    ErrorCode error_code = ErrorCode::kOk;
    CarSalesProcessor car_sales_processor;

    error_code = car_sales_processor.readCsv("../data/world_car_sales_1m.csv");
    if (error_code != ErrorCode::kOk) {
        return 0;
    }
    std::unordered_map<std::string, std::unordered_set<std::string>> column_values;

    // ========================= Q : 1 ========================================
    spdlog::info("==================================================================");
    spdlog::info("Question : 1");
    column_values = {
        {"country", {"China"}},
        {"manufacturer", {"Audi"}},
        {"sale_date", {"2025*"}}
    };
    auto china_audi_2025_sales = car_sales_processor.filterRowsByColumnValues(
        column_values, 
        {"country", "manufacturer", "sale_date"},
        WORKER_THREADS
    );
    spdlog::info("Number of cars sold by 'Audi' in China in 2025 : {}",  china_audi_2025_sales.size());



  // ========================= Q : 2 ========================================
    spdlog::info("==================================================================");
    spdlog::info("Question : 2");
    column_values = {
        {"manufacturer", {"BMW"}},
         {"sale_date", {"2025*"}}
    };
    auto bmw_sales = car_sales_processor.filterRowsByColumnValues(
        column_values, 
        {"manufacturer", "sale_date", "sale_price_usd"},
        WORKER_THREADS
    );
    auto [error_code_bmw_sales, bmw_sales_sum] = car_sales_processor.groupAndSumColumns(
        bmw_sales,
        "manufacturer",
        {"sale_price_usd"},
        WORKER_THREADS
    );
    if (error_code_bmw_sales != ErrorCode::kOk) {
        spdlog::error("Calculating total revenue generated by 'BMW' in 2025 failed!");
    } else {
        print_table(bmw_sales_sum, "Manufacturer");
        spdlog::info("Total revenue generated by 'BMW' in 2025 : {}",  bmw_sales_sum[0].second.at("sale_price_usd"));
    }

    // ========================= Q : 3 ========================================
    spdlog::info("==================================================================");
    spdlog::info("Question : 3");
    spdlog::info("Distribution of total revenue in European countries sorted from highest to lowest : ");
    column_values = {
        {"region", {"Europe"}}
    };
    auto europe_sales = car_sales_processor.filterRowsByColumnValues(
        column_values, 
        {"country", "region", "manufacturer", "sale_price_usd"},
        WORKER_THREADS
    );
    auto [error_code_europe, revenue_by_country] =
    car_sales_processor.groupAndSumColumns(
        europe_sales,
        "country",
        {"sale_price_usd"},
        WORKER_THREADS,
        true,
        "sale_price_usd"
    );
    if (error_code_europe != ErrorCode::kOk) {
        spdlog::error("Calculating total revenue generated by 'BMW' in 2025 failed!");
    } else {
        print_table(revenue_by_country, "Country");
    }
    return 0;
}
